#!/usr/bin/env bash
# loraham-images — seal a provisioned, MOUNTED root (offline, on the host).
# Removes all build-time PKI/secrets/host-keys/machine-id, verifies the seal invariant,
# and keeps ONLY the documented public onboarding defaults. Regeneration happens at first
# boot (fresh device PKI + host keys). Fails closed.
#
# Usage: seal.sh <root> <operator_user> <operator_password>
# shellcheck shell=bash
set -o errexit -o nounset -o pipefail
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$_here/lib.sh"

ROOT="${1:?root}"; OP="${2:?operator}"; OP_PW="${3:?password}"
RUNTIME="$ROOT/home/$OP/loraham-pi-control"

group_begin "seal: strip build-time PKI / secrets / host identity"

# --- LHPC PKI + generated webserver state (regenerated at first boot) --------
if [ -d "$RUNTIME/config/tls" ]; then
  log "removing LHPC PKI tree: config/tls"
  rm -rf "$RUNTIME/config/tls"
fi
# device-local secrets (git-ignored, regenerated on demand)
rm -f "$RUNTIME/config/secrets.toml"
# generated nginx state that references the removed certs (regenerated by webserver apply)
find "$RUNTIME/config" -maxdepth 3 -type f -name '*.nginx*' -delete 2>/dev/null || true
rm -rf "$RUNTIME/config/files/nginx" 2>/dev/null || true

# reset any exposed webserver desired-state back to loopback defaults
LOCAL_TOML="$RUNTIME/config/local.toml"
if [ -f "$LOCAL_TOML" ]; then
  sed -i -E 's/^(\s*remote_exposed\s*=\s*).*/\1false/' "$LOCAL_TOML" || true
  sed -i -E 's#^(\s*bind\s*=\s*).*#\1"127.0.0.1"#' "$LOCAL_TOML" || true
fi

# --- host identity: machine-id + ssh host keys ------------------------------
: > "$ROOT/etc/machine-id"
rm -f "$ROOT/var/lib/dbus/machine-id"
rm -f "$ROOT"/etc/ssh/ssh_host_* 2>/dev/null || true

# --- base-shipped private keys: inspect + regenerate-per-device --------------
# ssl-cert snakeoil key is generated per-machine at install; strip it (regenerated on demand).
rm -f "$ROOT"/etc/ssl/private/ssl-cert-snakeoil.key "$ROOT"/etc/ssl/certs/ssl-cert-snakeoil.pem 2>/dev/null || true
# wayvnc (Desktop) ships/generates device-specific VNC RSA + TLS keys; strip them so no shared
# VNC key ships in the image (wayvnc regenerates its rsa key per device on first run).
rm -f "$ROOT"/etc/wayvnc/*.pem "$ROOT"/etc/wayvnc/*.key 2>/dev/null || true

# pycryptodome ships throwaway test-vector private keys in its SelfTest suites (base
# python3-pycryptodome + the meshcore venvs). Static library test data — not device secrets,
# not runtime code. Remove them (also slims the image).
find "$ROOT" -type d \( -path '*/Crypto/SelfTest' -o -path '*/Cryptodome/SelfTest' \) \
  -prune -exec rm -rf {} + 2>/dev/null || true

group_end

# --- SEAL ASSERTIONS (fail closed) ------------------------------------------
group_begin "seal: assertions"

# (a) no actual private-key PEM BLOCK survives anywhere in the image.
# Narrow with grep (fast) to files carrying the marker, then confirm each is a REAL key
# block (marker + base64 body + END) — so library source that merely references the marker
# as a string literal (e.g. cryptography/ssh.py) is not a false positive.
mapfile -t candidates < <(grep -rIlE -- '-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----' "$ROOT" 2>/dev/null || true)
offenders=()
for f in "${candidates[@]}"; do
  if python3 - "$f" <<'PY'
import re, sys
try:
    data = open(sys.argv[1], "rb").read()
except Exception:
    sys.exit(1)
m = re.search(rb'-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----\s*\n(?:[A-Za-z0-9+/=]{24,}\s*\n)+-----END [A-Z0-9 ]*PRIVATE KEY-----', data)
sys.exit(0 if m else 1)
PY
  then offenders+=("$f"); fi
done
if [ "${#offenders[@]}" -gt 0 ]; then
  printf 'private-key material survived the seal:\n'; printf '  %s\n' "${offenders[@]}"
  die "seal failed: real private-key block(s) present"
fi
log "assert OK: no real private-key blocks in the image"

# (b) LHPC PKI absent
[ ! -d "$RUNTIME/config/tls" ] || die "seal failed: LHPC config/tls still present"
log "assert OK: LHPC PKI absent"

# (c) no ssh host keys
if ls "$ROOT"/etc/ssh/ssh_host_* >/dev/null 2>&1; then die "seal failed: ssh host keys present"; fi
log "assert OK: no ssh host keys"

# (d) machine-id empty
[ ! -s "$ROOT/etc/machine-id" ] || die "seal failed: /etc/machine-id not empty"
log "assert OK: machine-id cleared"

# (e) operator account hash corresponds to the documented onboarding password.
# Trixie hashes are yescrypt ($y$); recompute via libcrypt (crypt(3)), which supports it.
shadow_hash="$(awk -F: -v u="$OP" '$1==u{print $2}' "$ROOT/etc/shadow")"
[ -n "$shadow_hash" ] || die "seal failed: no shadow entry for $OP"
if OP_PW="$OP_PW" SHADOW="$shadow_hash" python3 - <<'PY'
import os, crypt, sys
pw, h = os.environ["OP_PW"], os.environ["SHADOW"]
sys.exit(0 if crypt.crypt(pw, h) == h else 1)
PY
then log "assert OK: operator password hash matches the documented default"
else die "seal failed: operator hash does not match the documented onboarding password"
fi

# (f) root-filesystem expansion is OWNED by lhpc-firstboot. The base's rpi-resize.service is
# ConditionFirstBoot=yes and disables itself the moment it runs — and it runs (and self-disables)
# during our nspawn provisioning boot, so it is already spent before the image reaches hardware.
# Relying on it (as an earlier "unit present" check did) left the fs unexpanded on real Pis.
# Assert instead that firstboot carries step_growroot (growpart + resize2fs) and is armed.
if grep -q 'step_growroot' "$ROOT/usr/local/sbin/lhpc-firstboot" 2>/dev/null; then
  log "assert OK: lhpc-firstboot owns rootfs expansion (step_growroot present)"
else
  die "seal failed: lhpc-firstboot lacks step_growroot — rootfs would never expand on hardware"
fi
# The base's EARLY grow (rpi-resize.service) should be re-armed too (disarm re-enables it after our
# build boot consumed it) so on-boot services get space before firstboot. Advisory: step_growroot
# guarantees expansion regardless, so a disabled rpi-resize is a warning, not a hard seal failure.
if [ -L "$ROOT/etc/systemd/system/sysinit.target.wants/rpi-resize.service" ]; then
  log "assert OK: rpi-resize.service re-armed for the real first boot"
else
  log "assert WARN: rpi-resize.service not re-armed — early on-boot services may hit the release-sized fs until step_growroot runs"
fi

group_end
log "SEAL OK"
