#!/usr/bin/env bash
# loraham-images — seal a provisioned, MOUNTED root (offline, on the host).
# Removes all build-time PKI/secrets/host-keys/machine-id, verifies the seal invariant,
# and keeps ONLY the documented public onboarding defaults. Regeneration happens at first
# boot (fresh device PKI + host keys). Fails closed.
#
# Usage: seal.sh <root> <operator_user> <operator_password> <overlay_dir>
# shellcheck shell=bash
set -o errexit -o nounset -o pipefail
_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib.sh
. "$_here/lib.sh"

ROOT="${1:?root}"; OP="${2:?operator}"; OP_PW="${3:?password}"
# Source tree the ownership assertion derives its path list from (see assertion (h)).
OVERLAY="${4:?overlay dir}"
RUNTIME="$ROOT/home/$OP/loraham-pi-control"

group_begin "seal: strip build-time PKI / secrets / host identity"

# --- LHPC PKI + generated webserver state (regenerated at first boot) --------
if [ -d "$RUNTIME/config/tls" ]; then
  log "removing LHPC PKI tree: config/tls"
  rm -rf "$RUNTIME/config/tls"
fi
# device-local secrets (git-ignored, regenerated on demand)
rm -f "$RUNTIME/config/secrets.toml"
# generated nginx state that references the removed certs (regenerated by webserver apply)
find "$RUNTIME/config" -maxdepth 3 -type f -name '*.nginx*' -delete 2>/dev/null || true
rm -rf "$RUNTIME/config/files/nginx" 2>/dev/null || true

# reset any exposed webserver desired-state back to loopback defaults
LOCAL_TOML="$RUNTIME/config/local.toml"
if [ -f "$LOCAL_TOML" ]; then
  sed -i -E 's/^(\s*remote_exposed\s*=\s*).*/\1false/' "$LOCAL_TOML" || true
  sed -i -E 's#^(\s*bind\s*=\s*).*#\1"127.0.0.1"#' "$LOCAL_TOML" || true
fi

# --- host identity: machine-id + ssh host keys ------------------------------
: > "$ROOT/etc/machine-id"
rm -f "$ROOT/var/lib/dbus/machine-id"
rm -f "$ROOT"/etc/ssh/ssh_host_* 2>/dev/null || true

# --- base-shipped private keys: inspect + regenerate-per-device --------------
# ssl-cert snakeoil key is generated per-machine at install; strip it (regenerated on demand).
rm -f "$ROOT"/etc/ssl/private/ssl-cert-snakeoil.key "$ROOT"/etc/ssl/certs/ssl-cert-snakeoil.pem 2>/dev/null || true
# wayvnc (Desktop) ships/generates device-specific VNC RSA + TLS keys; strip them so no shared
# VNC key ships in the image (wayvnc regenerates its rsa key per device on first run).
rm -f "$ROOT"/etc/wayvnc/*.pem "$ROOT"/etc/wayvnc/*.key 2>/dev/null || true

# pycryptodome ships throwaway test-vector private keys in its SelfTest suites (base
# python3-pycryptodome + the meshcore venvs). Static library test data — not device secrets,
# not runtime code. Remove them (also slims the image).
find "$ROOT" -type d \( -path '*/Crypto/SelfTest' -o -path '*/Cryptodome/SelfTest' \) \
  -prune -exec rm -rf {} + 2>/dev/null || true

group_end

# --- SEAL ASSERTIONS (fail closed) ------------------------------------------
group_begin "seal: assertions"

# (a) no actual private-key PEM BLOCK survives anywhere in the image.
# Narrow with grep (fast) to files carrying the marker, then confirm each is a REAL key
# block (marker + base64 body + END) — so library source that merely references the marker
# as a string literal (e.g. cryptography/ssh.py) is not a false positive.
mapfile -t candidates < <(grep -rIlE -- '-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----' "$ROOT" 2>/dev/null || true)
offenders=()
for f in "${candidates[@]}"; do
  if python3 - "$f" <<'PY'
import re, sys
try:
    data = open(sys.argv[1], "rb").read()
except Exception:
    sys.exit(1)
m = re.search(rb'-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----\s*\n(?:[A-Za-z0-9+/=]{24,}\s*\n)+-----END [A-Z0-9 ]*PRIVATE KEY-----', data)
sys.exit(0 if m else 1)
PY
  then offenders+=("$f"); fi
done
if [ "${#offenders[@]}" -gt 0 ]; then
  printf 'private-key material survived the seal:\n'; printf '  %s\n' "${offenders[@]}"
  die "seal failed: real private-key block(s) present"
fi
log "assert OK: no real private-key blocks in the image"

# (b) LHPC PKI absent
[ ! -d "$RUNTIME/config/tls" ] || die "seal failed: LHPC config/tls still present"
log "assert OK: LHPC PKI absent"

# (c) no ssh host keys
if ls "$ROOT"/etc/ssh/ssh_host_* >/dev/null 2>&1; then die "seal failed: ssh host keys present"; fi
log "assert OK: no ssh host keys"

# (d) machine-id empty
[ ! -s "$ROOT/etc/machine-id" ] || die "seal failed: /etc/machine-id not empty"
log "assert OK: machine-id cleared"

# (e) operator account hash corresponds to the documented onboarding password.
# Trixie hashes are yescrypt ($y$); recompute via libcrypt (crypt(3)), which supports it.
shadow_hash="$(awk -F: -v u="$OP" '$1==u{print $2}' "$ROOT/etc/shadow")"
[ -n "$shadow_hash" ] || die "seal failed: no shadow entry for $OP"
if OP_PW="$OP_PW" SHADOW="$shadow_hash" python3 - <<'PY'
# libcrypt via ctypes, NOT the stdlib `crypt` module: that module is removed in Python 3.13,
# so importing it would fail on a future runner image and take this fail-closed assertion with
# it. crypt(3) itself is what supports Trixie's yescrypt ($y$) hashes.
import ctypes, ctypes.util, os, sys
lib = ctypes.util.find_library("crypt") or "libcrypt.so.1"
c = ctypes.CDLL(lib)
c.crypt.restype = ctypes.c_char_p
c.crypt.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
pw, h = os.environ["OP_PW"].encode(), os.environ["SHADOW"].encode()
sys.exit(0 if c.crypt(pw, h) == h else 1)
PY
then log "assert OK: operator password hash matches the documented default"
else die "seal failed: operator hash does not match the documented onboarding password"
fi

# (f) root-filesystem expansion. The base's rpi-resize.service is ConditionFirstBoot=yes and
# disables itself the moment it runs — and it runs (and self-disables) during our nspawn
# provisioning boot, so it is already spent before the image reaches hardware. Relying on it (as
# an earlier "unit present" check did) left the fs unexpanded on real Pis. We instead OWN expansion
# with lhpc-growroot.service (fail-closed, ordered before firstboot). Assert HARD that the mechanism
# is actually shipped and armed, and that its required tool is present — a missing piece here is the
# exact class of bug that shipped an unexpandable image.
# Every overlay program, not a hand-maintained subset: lhpc-firstboot was never asserted, and
# the modes were mixed (growroot 100644 + an explicit chmod, the others 100755 via cp -a). One
# rule, so a fifth script cannot ship non-executable and unnoticed.
for _p in lhpc-firstboot lhpc-growroot lhpc-recovery lhpc-recovery-ap; do
  [ -x "$ROOT/usr/local/sbin/$_p" ] || die "seal failed: /usr/local/sbin/$_p missing or not executable"
done
[ -L "$ROOT/etc/systemd/system/sysinit.target.wants/lhpc-growroot.service" ] \
  || die "seal failed: lhpc-growroot.service not armed (sysinit.target.wants) — rootfs would never expand"
# "any of these paths exists" — NOT `ls a b c d` (that exits non-zero if ANY path is missing,
# which false-failed when growpart is only at /usr/bin).
if [ -e "$ROOT/usr/bin/growpart" ] || [ -e "$ROOT/bin/growpart" ] \
   || [ -e "$ROOT/usr/sbin/growpart" ] || [ -e "$ROOT/sbin/growpart" ]; then
  log "assert OK: lhpc-growroot armed + growpart present (rootfs expansion owned + verified)"
else
  die "seal failed: growpart not in image — lhpc-growroot cannot grow the partition"
fi
# firstboot must HARD-depend on a successful expansion, so it never writes to an unexpanded fs.
# Requires= propagates failure ONLY together with After= (ordering) — assert BOTH are present.
fbunit="$ROOT/etc/systemd/system/lhpc-firstboot.service"
[ -L "$ROOT/etc/systemd/system/sysinit.target.wants/lhpc-recovery.service" ] \
  || die "seal failed: lhpc-recovery.service not armed — a failed expansion would leave no way in"
grep -q '^Requires=' "$ROOT/etc/systemd/system/lhpc-recovery.service" \
  && die "seal failed: lhpc-recovery.service must not Require anything — that is the whole point"
[ -L "$ROOT/etc/systemd/system/multi-user.target.wants/lhpc-recovery-ap.service" ] \
  || die "seal failed: lhpc-recovery-ap.service not armed — a Wi-Fi-only box with a failed expansion would be unreachable"
grep -q '^Requires=' "$ROOT/etc/systemd/system/lhpc-recovery-ap.service" \
  && die "seal failed: lhpc-recovery-ap.service must not Require anything"

# Neither first-boot marker may ship. .firstboot-done would make the unit's ConditionPathExists
# skip onboarding entirely; .firstboot-finalizing is worse — firstboot would take the "completion
# was interrupted" path, mark itself done and disable, so the image would arrive looking
# commissioned while never having run a single step.
for _m in .firstboot-done .firstboot-finalizing; do
  [ -e "$ROOT/var/lib/lhpc/$_m" ] \
    && die "seal failed: $_m present in the image — first boot would be skipped"
done
log "assert OK: no first-boot markers in the image"
log "assert OK: lhpc-recovery armed, ordered before growroot, gated on nothing"
grep -q '^Requires=lhpc-growroot.service' "$fbunit" \
  || die "seal failed: lhpc-firstboot.service missing Requires=lhpc-growroot.service (failure would not block firstboot)"
grep -qE '^After=.*\blhpc-growroot\.service\b' "$fbunit" \
  || die "seal failed: lhpc-firstboot.service missing After=lhpc-growroot.service (Requires= without ordering does not block on failure)"
# SINGLE owner: the base rpi-resize.service must NOT be armed alongside lhpc-growroot — two
# unordered resizers on the same live partition is a race. Our build boot consumes+disables it;
# fail the seal if anything left it enabled.
if [ -L "$ROOT/etc/systemd/system/sysinit.target.wants/rpi-resize.service" ]; then
  die "seal failed: rpi-resize.service is still armed alongside lhpc-growroot — two concurrent resizers"
fi
log "assert OK: firstboot Requires growroot; rpi-resize not armed (single expansion owner)"

# (h) every object the overlay maps into the image is owned by root.
#
# DERIVED from the source tree, never a hand-kept list — unlike the executable check above, which
# names its four programs. A GitHub-hosted runner checks the repo out as uid/gid 1001, and inside
# the image uid 1001 is the OPERATOR, so a plain `cp -a` silently handed /, /etc and /usr to the
# account that ships with a documented public password. build.sh copies with
# --no-preserve=ownership,mode; this is the gate that keeps it that way, and it grows by itself
# when the overlay does.
#
# Checked WITHOUT dereferencing: `find` does not follow symlinks unless given -L, and `stat` would
# resolve them — a symlink's own ownership is what we are asserting. %U/%G are the NUMERIC ids
# (%u/%g would be the names); comparing numbers means a uid with no passwd entry cannot slip
# through, and no name lookup is involved at all.
if [ -d "$OVERLAY" ]; then
  bad=()
  while IFS= read -r -d '' rel; do
    dest="$ROOT/$rel"
    # Every source object is copied unconditionally and nothing removes one before the seal, so an
    # absent destination is a broken build, not a case to skip. For lhpc-recovery.service and
    # lhpc-recovery-ap.service this is the ONLY presence check in the file: the armed-symlink
    # assertions below test the .wants LINK, and their `grep ... && die` companions pass quietly
    # when the unit file they read is missing.
    [ -e "$dest" ] || [ -L "$dest" ] \
      || die "seal failed: overlay object /$rel is missing from the image"
    read -r u g < <(find "$dest" -maxdepth 0 -printf '%U %G\n')
    [ "$u" = 0 ] && [ "$g" = 0 ] || bad+=("/$rel ($u:$g)")
  done < <(find "$OVERLAY" -mindepth 1 -printf '%P\0')
  # ...and the destination root itself, which `cp -a src/. dst/` also stamps.
  read -r u g < <(find "$ROOT" -maxdepth 0 -printf '%U %G\n')
  [ "$u" = 0 ] && [ "$g" = 0 ] || bad+=("/ ($u:$g)")
  if [ "${#bad[@]}" -gt 0 ]; then
    printf 'overlay objects not owned by root:\n'; printf '  %s\n' "${bad[@]}"
    die "seal failed: overlay-mapped path(s) not owned by root — the operator account could replace them"
  fi
  log "assert OK: every overlay-mapped object (and /) is root-owned"
else
  die "seal failed: overlay dir '$OVERLAY' is not a directory — the ownership assertion cannot run"
fi

group_end
log "SEAL OK"
